fix: update quality gates
snyk/sweater-comb pull request #624
Opened 2024-06-04 08:12 UTC by corneliu-petrescu

2024-06-05 15:22 UTC, gablaxian approved these changes

2024-06-19 10:03 UTC, bikochan requested changes

2024-06-19 10:03 UTC, bikochan commented on .circleci/config.yml
> +          org: platformeng_api
org: not needed

2024-06-20 14:41 UTC, bikochan approved these changes

2024-06-21 09:43 UTC, merged

2024-06-21 09:59 UTC, snyksec commented
:tada: This PR is included in version 2.8.6 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@snyk/sweater-comb/v/2.8.6)
- [GitHub release](https://github.com/snyk/sweater-comb/releases/tag/v2.8.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: